export const INDIAN_BANK_OPTIONS: readonly string[] = [
  "AU Small Finance Bank Limited",
  "Axis Bank Limited",
  "Bandhan Bank Limited",
  "Bank of America",
  "Bank of Bahrain and Kuwait B.S.C.",
  "Bank of Baroda",
  "Bank of India",
  "Bank of Maharashtra",
  "Bank of Nova Scotia",
  "Barclays Bank PLC",
  "BNP Paribas",
  "Canara Bank",
  "Capital Small Finance Bank Limited",
  "Central Bank of India",
  "Chinatrust Commercial Bank",
  "Citibank N.A.",
  "City Union Bank Limited",
  "Commonwealth Bank of Australia",
  "Credit Agricole Corporate and Investment Bank",
  "Credit Suisse AG",
  "CSB Bank Limited",
  "CTBC Bank Co., Ltd.",
  "DBS Bank India Limited",
  "DCB Bank Limited",
  "Deutsche Bank",
  "Dhanlaxmi Bank Limited",
  "DMK Jaoli Bank",
  "Emirates NBD Bank PJSC",
  "Equitas Small Finance Bank Limited",
  "ESAF Small Finance Bank Limited",
  "Federal Bank Limited",
  "Fincare Small Finance Bank Limited",
  "Fino Payments Bank Limited",
  "First Abu Dhabi Bank PJSC",
  "HDFC Bank Limited",
  "HSBC Limited",
  "ICICI Bank Limited",
  "IDBI Bank Limited",
  "IDFC FIRST Bank Limited",
  "India Post Payments Bank Limited",
  "Indian Bank",
  "Indian Overseas Bank",
  "IndusInd Bank Limited",
  "Industrial Bank of Korea",
  "Industrial & Commercial Bank of China Limited",
  "Jammu & Kashmir Bank Limited",
  "Jana Small Finance Bank Limited",
  "Jio Payments Bank Limited",
  "JP Morgan Chase Bank N.A.",
  "Karnataka Bank Limited",
  "Karur Vysya Bank Limited",
  "KEB Hana Bank",
  "Kookmin Bank",
  "Kotak Mahindra Bank Limited",
  "Krung Thai Bank Public Company Limited",
  "Mashreq Bank PSC",
  "Mizuho Bank Limited",
  "MUFG Bank Ltd.",
  "Nainital Bank Limited",
  "National Australia Bank",
  "North East Small Finance Bank Limited",
  "Paytm Payments Bank Limited",
  "Punjab & Sind Bank",
  "Punjab National Bank",
  "Qatar National Bank SAQ",
  "RBL Bank Limited",
  "SBM Bank (India) Limited",
  "Shinhan Bank",
  "South Indian Bank Limited",
  "Standard Chartered Bank",
  "State Bank of India",
  "Sumitomo Mitsui Banking Corporation",
  "Suryoday Small Finance Bank Limited",
  "Tamilnad Mercantile Bank Limited",
  "UCO Bank",
  "Ujjivan Small Finance Bank Limited",
  "Union Bank of India",
  "United Overseas Bank Limited",
  "Unity Small Finance Bank Limited",
  "Utkarsh Small Finance Bank Limited",
  "Yes Bank Limited",
  "Abhyudaya Cooperative Bank Limited",
  "Ahmedabad Mercantile Cooperative Bank Limited",
  "Akola Urban Cooperative Bank Limited",
  "Apna Sahakari Bank Limited",
  "Bassein Catholic Cooperative Bank Limited",
  "Bharat Cooperative Bank (Mumbai) Limited",
  "Bombay Mercantile Cooperative Bank Limited",
  "Citizen Credit Cooperative Bank Limited",
  "Cosmos Cooperative Bank Limited",
  "Dombivli Nagari Sahakari Bank Limited",
  "Greater Bombay Cooperative Bank Limited",
  "Jalgaon Janata Sahakari Bank Limited",
  "Janakalyan Sahakari Bank Limited",
  "Janaseva Sahakari Bank (Borivli) Limited",
  "Kalupur Commercial Cooperative Bank Limited",
  "Kalyan Janata Sahakari Bank Limited",
  "Kapole Cooperative Bank Limited",
  "Mahanagar Cooperative Bank Limited",
  "Mehsana Urban Cooperative Bank Limited",
  "Nagar Urban Cooperative Bank Limited",
  "Nasik Merchants Cooperative Bank Limited",
  "NKGSB Cooperative Bank Limited",
  "Pravara Sahakari Bank Limited",
  "Punjab & Maharashtra Cooperative Bank Limited",
  "Rupee Cooperative Bank Limited",
  "Saraswat Cooperative Bank Limited",
  "Shikshak Cooperative Bank Limited",
  "Solapur Janata Sahakari Bank Limited",
  "Thane Bharat Sahakari Bank Limited",
  "TNSC Bank Limited",
].sort((a, b) => a.localeCompare(b));
